Repository GSG-G10/gifty, pull requests merged in 2021-10, with the labels that each got.

#8 5 create server
  client/package-lock.json
  client/src/App.jsx
  client/src/index.jsx
  package-lock.json
  server/app.js
  server/index.js
  server/routes/index.js
Labels: Done

#36 06 database schema
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
Labels: Awaiting Review

#37 connect the database with the server
  client/package-lock.json
  client/package.json
  package.json
  server/app.js
  server/database/connection/index.js
Labels: Awaiting Review

#38 write authentication middleware
  server/middlewares/checkUser.js
  server/middlewares/index.js
Labels: Awaiting Review

#39 14 get product
  server/controllers/getProduct.js
  server/controllers/index.js
  server/database/queries/getProductQuery.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Awaiting Review

#41 get-products-from-database
  client/package-lock.json
  package-lock.json
  package.json
  server/controllers/getProducts.js
  server/controllers/index.js
  server/database/connection/index.js
  server/database/queries/getProductsQuiery.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Awaiting Review

#42 16 delete product
  server/controllers/deleteProduct.js
  server/controllers/index.js
  server/database/queries/deleteProductQuery.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Awaiting Review

#40 10 signup route
  package-lock.json
  package.json
  server/controllers/addUser.js
  server/controllers/index.js
  server/database/queries/addUserQuery.js
  server/database/queries/index.js
  server/routes/index.js
  server/utils/validations/hashPasswords.js
  server/utils/validations/index.js
  server/utils/validations/signupSchema.js
Labels: Awaiting Review

#43 11 sign in
  client/package-lock.json
  client/package.json
  package-lock.json
  server/app.js
  server/controllers/addUser.js
  server/controllers/getProducts.js
  server/controllers/index.js
  server/controllers/signIn.js
  server/database/config/build.sql
  server/database/queries/getProductsQuiery.js
  server/database/queries/getUserData.js
  server/database/queries/getUserId.js
  server/database/queries/index.js
  server/middlewares/index.js
  server/middlewares/setCookies.js
  server/routes/index.js
  server/utils/validations/comparePassword.js
  server/utils/validations/index.js
  server/utils/validations/signInSchema.js
Labels: Done

#44 write user cart product query and handle its route
  server/controllers/getProducts.js
  server/controllers/getUserCart.js
  server/controllers/index.js
  server/database/queries/getProductsQuery.js
  server/database/queries/getUserCartQuery.js
  server/database/queries/index.js
  server/middlewares/checkUser.js
  server/middlewares/setCookies.js
  server/routes/index.js
Labels: Awaiting Review

#45 add to cart
  client/package-lock.json
  client/package.json
  server/controllers/addToCart.js
  server/controllers/index.js
  server/database/queries/addToCartquery.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Changes Requested

#46 Fix eslint errors and clean code
  client/src/components/common/index.jsx
  package-lock.json
  server/controllers/addToCart.js
  server/controllers/addUser.js
  server/controllers/deleteProduct.js
  server/controllers/getProduct.js
  server/controllers/getProducts.js
  server/controllers/getUserCart.js
  server/controllers/index.js
  server/controllers/signIn.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/connection/index.js
  server/database/queries/addToCartquery.js
  server/database/queries/index.js
  server/middlewares/checkUser.js
  server/middlewares/index.js
  server/middlewares/setCookies.js
  server/routes/index.js
  server/utils/validations/comparePassword.js
  server/utils/validations/index.js
Labels: Awaiting Review

#47 Create Slider Component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/slider/index.jsx
  client/src/pages/landing/index.jsx
Labels: Awaiting Review

#49 23 filter component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Filter/index.jsx
  client/src/components/Filter/style.css
  client/src/pages/landing/index.jsx
  client/src/pages/landing/style.css
  server/app.js
Labels: Awaiting Review

#48 create products components
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/ProductsContainer/ProductCard/index.jsx
  client/src/components/ProductsContainer/ProductCard/style.css
  client/src/components/ProductsContainer/index.jsx
  client/src/components/ProductsContainer/style.css
  client/src/components/common/SectionTitle/index.jsx
  client/src/components/common/SectionTitle/style.css
  client/src/components/slider/index.jsx
Labels: Awaiting Review

#52 29 related products
  client/package-lock.json
  client/package.json
  client/src/components/RelatedProducts/index.jsx
  client/src/components/RelatedProducts/style.css
Labels: Awaiting Review

#54 28 tab component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Tab/index.jsx
  client/src/components/Tab/rate.png
  client/src/components/Tab/style.css
  server/app.js
  server/controllers/addComment.js
  server/controllers/getComments.js
  server/controllers/index.js
  server/database/queries/addCommentQuery.js
  server/database/queries/getCommentsQuery.js
  server/database/queries/index.js
  server/middlewares/checkUser.js
  server/routes/index.js
Labels: Done

#55 cart-page
  client/.eslintrc.json
  client/package.json
  client/src/App.jsx
  client/src/pages/Cart/index.jsx
  client/src/pages/Cart/style.css
  package-lock.json
  package.json
Labels: Awaiting Review

#61 33 product page
  client/src/App.jsx
  client/src/components/RelatedProducts/index.jsx
  client/src/components/Tab/index.jsx
  client/src/components/Tab/style.css
  client/src/components/overview/index.css
  client/src/components/overview/index.jsx
  client/src/pages/landing/index.jsx
  client/src/pages/product/index.jsx
  package-lock.json
  package.json
  server/controllers/getUserCart.js
Labels: Awaiting Review

#63 fix cart page
  client/src/App.jsx
  client/src/components/common/Header/index.jsx
  client/src/components/common/Header/style.css
  client/src/components/overview/index.jsx
  client/src/pages/Cart/index.jsx
  client/src/pages/Cart/style.css
  client/src/pages/Register/style.css
  server/controllers/deleteProduct.js
  server/controllers/index.js
  server/database/queries/getUserCartQuery.js
Labels: Awaiting Review
